name: AfterLife
main: com.steve.nukkit.AfterLife.Main
version: 2.0.1
api: [1.0.0]
author: Atom
softdepend:
  - AliasPro
depend:
  - NukkitDB

permissions:
  leaderboard.create:
    default: op
    description: allows user to create and set leaderboards