name: AfterLife
main: com.steve.nukkit.AfterLife.Main
version: 2.2.3
api: [1.0.0]
author: Atom
depend:
  - NukkitDB
  - PlayerAPI

permissions:
  leaderboard.create:
    default: op
    description: allows user to create and set leaderboards