name: Afterlife
main: Afterlife.Main
version: 3.0.4
api: 1.0.9
author: Atom
depend:
  - NukkitDB
  - PlayerAPI
  - FormAPI

permissions:
  leaderboard.create:
    default: op
    description: allows user to create and set leaderboards